import {captionFor} from './captions.js';
const database = () => new Promise((resolve,reject)=>{const r=indexedDB.open('wrzutka',1);r.onupgradeneeded=()=>{r.result.createObjectStore('media');r.result.createObjectStore('jobs',{keyPath:'id'});};r.onerror=()=>reject(r.error);r.onsuccess=()=>resolve(r.result);});
export async function transact(store,mode,action){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);const request=action(tx.objectStore(store));tx.oncomplete=()=>resolve(request?.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Nie udało się zapisać danych.'));});}finally{db.close();}}
export const saveMedia=(id,file)=>transact('media','readwrite',s=>s.put(file,id));
export const getMedia=id=>transact('media','readonly',s=>s.get(id));
export const removeMedia=id=>transact('media','readwrite',s=>s.delete(id));
export const getJob=id=>transact('jobs','readonly',s=>s.get(id));
export const saveJob=job=>transact('jobs','readwrite',s=>s.put(job));
export const listJobs=()=>transact('jobs','readonly',s=>s.getAll());
export async function createJob(job){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('jobs','readwrite'),s=tx.objectStore('jobs'),r=s.getAll();r.onsuccess=()=>{try{const old=r.result;if(old.some(j=>j.targets.some(t=>['pending','preparing','uploading','ready','committing'].includes(t.status))))throw new Error('Najpierw zakończ bieżącą wysyłkę.');if(old.some(j=>j.digest===job.digest&&j.privacy===job.privacy&&j.targets.some(t=>job.targets.some(n=>n.platform===t.platform)&&captionFor(j,t.platform)===captionFor(job,t.platform)&&t.committedAt)))throw new Error('Ten film z tym opisem był już wysyłany. Sprawdź historię, aby uniknąć duplikatu.');s.add(job);}catch(e){reject(e);tx.abort();}};tx.oncomplete=()=>resolve(job);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Przerwano zapis wysyłki.'));});}finally{db.close();}}
// Read-modify-write in one transaction prevents concurrent platform updates from losing each other.
export async function mutateJob(id,change){const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('jobs','readwrite');const s=tx.objectStore('jobs');let result;const r=s.get(id);r.onsuccess=()=>{try{if(!r.result)throw new Error('Nie znaleziono wysyłki.');result=change(r.result);s.put(result);}catch(e){reject(e);tx.abort();}};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Zapis przerwany.'));});}finally{db.close();}}
